version: 1.0.{build}
image: Visual Studio 2022
branches:
  only:
    - main
environment:
  deploy_username:
    secure: ZumRpgIeGcRgW3H7yXK0bQ==
  deploy_password:
    secure: SFAvHfsz398LTl83QbS5gw==
  deploy_publish_url_1:
    secure: K69zP3wjxwDVH7s/sC4OthodaOPs3etcQKSoMEi3J24Zzy/Pqe9QtILQ+TIhpLoJDz6QebuZDVdqciF20w136YeX6zpfMUBdcoVxkrySUdQ=
  deploy_publish_url_2:
    secure: Z3kFMmPS+/3jEb5uz8UtB3IsEwaE+Vyv1TS5Ry3tumcQSr0Q1PooCrfztHFGA5CVScwWtIHuv7GPMn7OIANfIE/Z558TKobWJ5AGPrDMkvk=
  ms_deploy_site_1:
    secure: kdhuPVSl0krNFGjfcNUmBMLohWaq8nbOx5Ven52IcoU=
  ms_deploy_site_2:
    secure: Pf9YKHPQdl46IZWXnY91FKlQ5RlIjuikjHk855wYG5Y=
  db_server:
    secure: GENtSiIHJlcMVdOs9CjeQw==
  db_name:
    secure: WrPAgPpTyM3R6EL58lnCDg==
  db_username:
    secure: WrPAgPpTyM3R6EL58lnCDg==
  db_password:
    secure: SFAvHfsz398LTl83QbS5gw==
install:
  - ps: >-
      $file = "./Api/appsettings.Production.json";
      (Get-Content $file).Replace("{db_server}", $env:db_server).Replace("{db_name}", $env:db_name).Replace("{db_username}", $env:db_username).Replace("{db_password}", $env:db_password) | Set-Content $file
build_script:
  - cmd: dotnet publish --framework net8.0 /p:EnvironmentName=Production --self-contained true -r win-x64 Api --output %appveyor_build_folder%\dist
test_script:
  # Ejecuta tests
  - dotnet test --configuration Release --runtime win-x64
before_deploy:
  # Aplica migraciones pendientes
  - cd Api
  - dotnet tool install dotnet-ef --global --version 8.0.0
  - ps: $DefaultConnectionString = (Get-Content appsettings.Production.json | ConvertFrom-Json).ConnectionStrings.Default
  - ps: dotnet ef database update --connection $DefaultConnectionString
artifacts:
  - path: dist
deploy:
  - provider: WebDeploy
    remove_files: true
    skip_dirs: \\App_Data;\\Imagenes;\\logs;\\aspnet_client;\\wwwroot;
    server: $(deploy_publish_url_1)
    website: $(ms_deploy_site_1)
    username: $(deploy_username)
    password: $(deploy_password)
    ntlm: false
  - provider: WebDeploy
    remove_files: true
    skip_dirs: \\App_Data;\\Imagenes;\\logs;\\aspnet_client;\\wwwroot;
    server: $(deploy_publish_url_2)
    website: $(ms_deploy_site_2)
    username: $(deploy_username)
    password: $(deploy_password)
    ntlm: false
