// <auto-generated />
using System;
using Api.Persistencia._Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408083808_ConfiguracionSeed")]
    partial class ConfiguracionSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Core.Entidades.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("EsTechado")
                        .HasColumnType("bit");

                    b.Property<string>("Localidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Clubs", "dbo");
                });

            modelBuilder.Entity("Api.Core.Entidades.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("FichajeEstaHabilitado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Configuracion", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FichajeEstaHabilitado = true
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.Delegado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("TelefonoCelular")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.ToTable("Delegados", "dbo");
                });

            modelBuilder.Entity("Api.Core.Entidades.DelegadoClub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("DelegadoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoDelegadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("EstadoDelegadoId");

                    b.HasIndex("DelegadoId", "ClubId")
                        .IsUnique();

                    b.ToTable("DelegadoClub", "dbo");
                });

            modelBuilder.Entity("Api.Core.Entidades.DniExpulsadoDeLaLiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Explicacion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.ToTable("DnisExpulsadosDeLaLiga", "dbo");
                });

            modelBuilder.Entity("Api.Core.Entidades.EntidadesConValoresPredefinidos.Color", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("_Color", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Nombre = "Negro"
                        },
                        new
                        {
                            Id = 1,
                            Nombre = "Azul"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Rojo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Verde"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Amarillo"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Naranja"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Violeta"
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.EntidadesConValoresPredefinidos.EstadoDelegado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("_EstadoDelegado", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Pendiente de aprobación"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Rechazado"
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Activo"
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.EntidadesConValoresPredefinidos.EstadoFase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("_EstadoFase", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Estado = "Inicio pendiente"
                        },
                        new
                        {
                            Id = 200,
                            Estado = "En curso"
                        },
                        new
                        {
                            Id = 300,
                            Estado = "Finalizada"
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.EntidadesConValoresPredefinidos.EstadoJugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("_EstadoJugador", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Fichaje pendiente de aprobación"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Fichaje rechazado"
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Activo"
                        },
                        new
                        {
                            Id = 4,
                            Estado = "Suspendido"
                        },
                        new
                        {
                            Id = 5,
                            Estado = "Inhabilitado"
                        },
                        new
                        {
                            Id = 6,
                            Estado = "Aprobado pendiente de pago"
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.EntidadesConValoresPredefinidos.FaseFormato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("_FaseFormato", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Todos contra todos"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Eliminación directa"
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.EntidadesConValoresPredefinidos.InstanciaEliminacionDirecta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("_InstanciaEliminacionDirecta", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 16,
                            Nombre = "Octavos de final"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Cuartos de final"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Semifinal"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Final"
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.EntidadesConValoresPredefinidos.LocalVisitante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("_LocalVisitante", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Local"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Visitante"
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.EntidadesConValoresPredefinidos.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("_Rol", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Usuario"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Consulta"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Delegado"
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Equipos", "dbo");
                });

            modelBuilder.Entity("Api.Core.Entidades.EquipoZona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("ZonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.HasIndex("EquipoId", "ZonaId")
                        .IsUnique();

                    b.ToTable("EquipoZona", "dbo");
                });

            modelBuilder.Entity("Api.Core.Entidades.Fase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsVisibleEnApp")
                        .HasColumnType("bit");

                    b.Property<int>("EstadoFaseId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("TipoFase")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("TorneoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoFaseId");

                    b.HasIndex("TorneoId", "Numero")
                        .IsUnique();

                    b.ToTable("Fases", "dbo");

                    b.HasDiscriminator<string>("TipoFase").HasValue("Fase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Api.Core.Entidades.Fecha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Dia")
                        .HasColumnType("date");

                    b.Property<bool>("EsVisibleEnApp")
                        .HasColumnType("bit");

                    b.Property<string>("TipoFecha")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("ZonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fechas", "dbo");

                    b.HasDiscriminator<string>("TipoFecha").HasValue("Fecha");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Api.Core.Entidades.FixtureAlgoritmo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDeEquipos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FixtureAlgoritmos", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadDeEquipos = 4,
                            Nombre = "Clásico"
                        },
                        new
                        {
                            Id = 2,
                            CantidadDeEquipos = 8,
                            Nombre = "Apertura"
                        },
                        new
                        {
                            Id = 3,
                            CantidadDeEquipos = 10,
                            Nombre = "Apertura"
                        },
                        new
                        {
                            Id = 4,
                            CantidadDeEquipos = 12,
                            Nombre = "Apertura"
                        },
                        new
                        {
                            Id = 5,
                            CantidadDeEquipos = 14,
                            Nombre = "Apertura"
                        },
                        new
                        {
                            Id = 6,
                            CantidadDeEquipos = 16,
                            Nombre = "Apertura"
                        },
                        new
                        {
                            Id = 7,
                            CantidadDeEquipos = 4,
                            Nombre = "Champions"
                        },
                        new
                        {
                            Id = 8,
                            CantidadDeEquipos = 8,
                            Nombre = "Clausura"
                        },
                        new
                        {
                            Id = 9,
                            CantidadDeEquipos = 10,
                            Nombre = "Clausura"
                        },
                        new
                        {
                            Id = 10,
                            CantidadDeEquipos = 12,
                            Nombre = "Clausura"
                        },
                        new
                        {
                            Id = 11,
                            CantidadDeEquipos = 14,
                            Nombre = "Clausura"
                        },
                        new
                        {
                            Id = 12,
                            CantidadDeEquipos = 16,
                            Nombre = "Clausura"
                        },
                        new
                        {
                            Id = 13,
                            CantidadDeEquipos = 6,
                            Nombre = "Apertura"
                        },
                        new
                        {
                            Id = 14,
                            CantidadDeEquipos = 6,
                            Nombre = "Clausura"
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.FixtureAlgoritmoFecha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoLocal")
                        .HasColumnType("int");

                    b.Property<int>("EquipoVisitante")
                        .HasColumnType("int");

                    b.Property<int>("Fecha")
                        .HasColumnType("int");

                    b.Property<int>("FixtureAlgoritmoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FixtureAlgoritmoId", "Fecha", "EquipoLocal", "EquipoVisitante")
                        .IsUnique();

                    b.ToTable("FixtureAlgoritmoFecha", "dbo");
                });

            modelBuilder.Entity("Api.Core.Entidades.HistorialDePagos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("JugadorEquipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JugadorEquipoId")
                        .IsUnique();

                    b.ToTable("HistorialDePagos", "dbo");
                });

            modelBuilder.Entity("Api.Core.Entidades.Jornada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FechaId")
                        .HasColumnType("int");

                    b.Property<bool>("ResultadosVerificados")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("FechaId");

                    b.ToTable("Jornadas", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Jornada_Tipo_Valido", "([Tipo] = N'Normal' AND [LocalEquipoId] IS NOT NULL AND [VisitanteEquipoId] IS NOT NULL AND [LocalEquipoId] <> [VisitanteEquipoId] AND [EquipoId] IS NULL AND [EquipoLocalId] IS NULL AND [LocalOVisitanteId] IS NULL)\n    OR\n    ([Tipo] = N'Libre' AND [EquipoLocalId] IS NOT NULL AND [LocalEquipoId] IS NULL AND [VisitanteEquipoId] IS NULL AND [EquipoId] IS NULL AND [LocalOVisitanteId] IS NULL)\n    OR\n    ([Tipo] = N'Interzonal' AND [EquipoId] IS NOT NULL AND [LocalOVisitanteId] IS NOT NULL AND [LocalEquipoId] IS NULL AND [VisitanteEquipoId] IS NULL AND [EquipoLocalId] IS NULL)\n    OR\n    ([Tipo] = N'SinEquipos' AND [LocalEquipoId] IS NULL AND [VisitanteEquipoId] IS NULL AND [EquipoId] IS NULL AND [EquipoLocalId] IS NULL AND [LocalOVisitanteId] IS NULL)");
                        });

                    b.HasDiscriminator<string>("Tipo").HasValue("Jornada");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Api.Core.Entidades.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.ToTable("Jugadores", "dbo");
                });

            modelBuilder.Entity("Api.Core.Entidades.JugadorEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoJugadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFichaje")
                        .HasColumnType("datetime2");

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TarjetasAmarillas")
                        .HasColumnType("int");

                    b.Property<int>("TarjetasRojas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoJugadorId");

                    b.HasIndex("JugadorId");

                    b.HasIndex("EquipoId", "JugadorId")
                        .IsUnique();

                    b.ToTable("JugadorEquipo", "dbo");
                });

            modelBuilder.Entity("Api.Core.Entidades.LeyendaTablaPosiciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Leyenda")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("QuitaDePuntos")
                        .HasColumnType("int");

                    b.Property<int>("ZonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("ZonaId", "CategoriaId")
                        .IsUnique()
                        .HasFilter("[EquipoId] IS NULL");

                    b.HasIndex("ZonaId", "CategoriaId", "EquipoId")
                        .IsUnique()
                        .HasFilter("[EquipoId] IS NOT NULL");

                    b.ToTable("LeyendaTablaPosiciones", "dbo");
                });

            modelBuilder.Entity("Api.Core.Entidades.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("JornadaId")
                        .HasColumnType("int");

                    b.Property<string>("PenalesLocal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PenalesVisitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultadoLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultadoVisitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("JornadaId", "CategoriaId")
                        .IsUnique()
                        .HasDatabaseName("IX_Partidos_JornadaId_CategoriaId");

                    b.ToTable("Partidos", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Partido_PenalesLocal_Valido", "([PenalesLocal] IS NULL OR ([PenalesLocal] NOT LIKE '%[^0-9]%' AND LEN([PenalesLocal]) > 0))");

                            t.HasCheckConstraint("CK_Partido_PenalesVisitante_Valido", "([PenalesVisitante] IS NULL OR ([PenalesVisitante] NOT LIKE '%[^0-9]%' AND LEN([PenalesVisitante]) > 0))");

                            t.HasCheckConstraint("CK_Partido_ResultadoLocal_Valido", "([ResultadoLocal] NOT LIKE '%[^0-9]%' OR [ResultadoLocal] IN (N'NP', N'S', N'P', N'GP', N'PP'))");

                            t.HasCheckConstraint("CK_Partido_ResultadoVisitante_Valido", "([ResultadoVisitante] NOT LIKE '%[^0-9]%' OR [ResultadoVisitante] IN (N'NP', N'S', N'P', N'GP', N'PP'))");
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.Torneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<bool>("EsVisibleEnApp")
                        .HasColumnType("bit");

                    b.Property<int?>("FaseAperturaId")
                        .HasColumnType("int");

                    b.Property<int?>("FaseClausuraId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("SeVenLosGolesEnTablaDePosiciones")
                        .HasColumnType("bit");

                    b.Property<int>("TorneoAgrupadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FaseAperturaId");

                    b.HasIndex("FaseClausuraId");

                    b.HasIndex("TorneoAgrupadorId");

                    b.HasIndex("Nombre", "Anio", "TorneoAgrupadorId")
                        .IsUnique();

                    b.ToTable("Torneos", "dbo");
                });

            modelBuilder.Entity("Api.Core.Entidades.TorneoAgrupador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<bool>("EsVisibleEnApp")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.ToTable("TorneoAgrupadores", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorId = 0,
                            EsVisibleEnApp = false,
                            Nombre = "General"
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.TorneoCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioDesde")
                        .HasColumnType("int");

                    b.Property<int>("AnioHasta")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TorneoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TorneoId");

                    b.ToTable("TorneoCategorias", "dbo");
                });

            modelBuilder.Entity("Api.Core.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DelegadoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("DelegadoId")
                        .IsUnique()
                        .HasFilter("[DelegadoId] IS NOT NULL");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreUsuario = "mati",
                            Password = "$2a$12$GyXIlB5JZ77AALRmlPVMie5fuz.kTVlB.PVm7H3RNqzg46Nx2ymje",
                            RolId = 0
                        },
                        new
                        {
                            Id = 2,
                            NombreUsuario = "pipa",
                            Password = "$2a$12$7OLvWiL4v6gwsIydo1Uob.ceKDqD91IWBCrt2rbOBRmtPZce6Bldi",
                            RolId = 1
                        },
                        new
                        {
                            Id = 101,
                            NombreUsuario = "consulta",
                            Password = "$2a$12$9jtg9uujsVDh8yW9WkXN6OtO9Nfn9CX7k7FFg.X1dpebyYhAz6wMa",
                            RolId = 3
                        },
                        new
                        {
                            Id = 1000,
                            NombreUsuario = "eze",
                            Password = "$2a$12$RGfXR1OqNh/NdsVKI757c.yy89KP7jZSF38L/Tnp8cKrq3oJGCjYq",
                            RolId = 1
                        },
                        new
                        {
                            Id = 1001,
                            NombreUsuario = "lucas",
                            Password = "$2a$12$OLMR8mWP6jUVhjaL1NlV5uxQFOUNey229uQ3UMPjJtVxNvKVjtxmK",
                            RolId = 1
                        },
                        new
                        {
                            Id = 1002,
                            NombreUsuario = "elias",
                            Password = "$2a$12$uMUdEC2IlTiK5da9QAfGIOycemWifwv1M27EbIIulcjt8kPaLz3SC",
                            RolId = 1
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FaseId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoZona")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.ToTable("Zonas", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Zonas_EliminacionDirecta_TieneCategoria", "([TipoZona] <> N'EliminacionDirecta') OR ([CategoriaId] IS NOT NULL)");
                        });

                    b.HasDiscriminator<string>("TipoZona").HasValue("Zona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Api.Core.Entidades.FaseEliminacionDirecta", b =>
                {
                    b.HasBaseType("Api.Core.Entidades.Fase");

                    b.HasDiscriminator().HasValue("EliminacionDirecta");
                });

            modelBuilder.Entity("Api.Core.Entidades.FaseTodosContraTodos", b =>
                {
                    b.HasBaseType("Api.Core.Entidades.Fase");

                    b.HasDiscriminator().HasValue("TodosContraTodos");
                });

            modelBuilder.Entity("Api.Core.Entidades.FechaEliminacionDirecta", b =>
                {
                    b.HasBaseType("Api.Core.Entidades.Fecha");

                    b.Property<int>("InstanciaId")
                        .HasColumnType("int");

                    b.HasIndex("InstanciaId");

                    b.HasIndex("ZonaId", "InstanciaId")
                        .IsUnique()
                        .HasFilter("[InstanciaId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("EliminacionDirecta");
                });

            modelBuilder.Entity("Api.Core.Entidades.FechaTodosContraTodos", b =>
                {
                    b.HasBaseType("Api.Core.Entidades.Fecha");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasIndex("ZonaId", "Numero")
                        .IsUnique()
                        .HasFilter("[Numero] IS NOT NULL");

                    b.HasDiscriminator().HasValue("TodosContraTodos");
                });

            modelBuilder.Entity("Api.Core.Entidades.JornadaInterzonal", b =>
                {
                    b.HasBaseType("Api.Core.Entidades.Jornada");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("LocalOVisitanteId")
                        .HasColumnType("int");

                    b.HasIndex("EquipoId");

                    b.HasIndex("LocalOVisitanteId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Jornada_Tipo_Valido", "([Tipo] = N'Normal' AND [LocalEquipoId] IS NOT NULL AND [VisitanteEquipoId] IS NOT NULL AND [LocalEquipoId] <> [VisitanteEquipoId] AND [EquipoId] IS NULL AND [EquipoLocalId] IS NULL AND [LocalOVisitanteId] IS NULL)\n    OR\n    ([Tipo] = N'Libre' AND [EquipoLocalId] IS NOT NULL AND [LocalEquipoId] IS NULL AND [VisitanteEquipoId] IS NULL AND [EquipoId] IS NULL AND [LocalOVisitanteId] IS NULL)\n    OR\n    ([Tipo] = N'Interzonal' AND [EquipoId] IS NOT NULL AND [LocalOVisitanteId] IS NOT NULL AND [LocalEquipoId] IS NULL AND [VisitanteEquipoId] IS NULL AND [EquipoLocalId] IS NULL)\n    OR\n    ([Tipo] = N'SinEquipos' AND [LocalEquipoId] IS NULL AND [VisitanteEquipoId] IS NULL AND [EquipoId] IS NULL AND [EquipoLocalId] IS NULL AND [LocalOVisitanteId] IS NULL)");
                        });

                    b.HasDiscriminator().HasValue("Interzonal");
                });

            modelBuilder.Entity("Api.Core.Entidades.JornadaLibre", b =>
                {
                    b.HasBaseType("Api.Core.Entidades.Jornada");

                    b.Property<int>("EquipoLocalId")
                        .HasColumnType("int");

                    b.HasIndex("EquipoLocalId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Jornada_Tipo_Valido", "([Tipo] = N'Normal' AND [LocalEquipoId] IS NOT NULL AND [VisitanteEquipoId] IS NOT NULL AND [LocalEquipoId] <> [VisitanteEquipoId] AND [EquipoId] IS NULL AND [EquipoLocalId] IS NULL AND [LocalOVisitanteId] IS NULL)\n    OR\n    ([Tipo] = N'Libre' AND [EquipoLocalId] IS NOT NULL AND [LocalEquipoId] IS NULL AND [VisitanteEquipoId] IS NULL AND [EquipoId] IS NULL AND [LocalOVisitanteId] IS NULL)\n    OR\n    ([Tipo] = N'Interzonal' AND [EquipoId] IS NOT NULL AND [LocalOVisitanteId] IS NOT NULL AND [LocalEquipoId] IS NULL AND [VisitanteEquipoId] IS NULL AND [EquipoLocalId] IS NULL)\n    OR\n    ([Tipo] = N'SinEquipos' AND [LocalEquipoId] IS NULL AND [VisitanteEquipoId] IS NULL AND [EquipoId] IS NULL AND [EquipoLocalId] IS NULL AND [LocalOVisitanteId] IS NULL)");
                        });

                    b.HasDiscriminator().HasValue("Libre");
                });

            modelBuilder.Entity("Api.Core.Entidades.JornadaNormal", b =>
                {
                    b.HasBaseType("Api.Core.Entidades.Jornada");

                    b.Property<int>("LocalEquipoId")
                        .HasColumnType("int");

                    b.Property<int>("VisitanteEquipoId")
                        .HasColumnType("int");

                    b.HasIndex("LocalEquipoId");

                    b.HasIndex("VisitanteEquipoId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Jornada_Tipo_Valido", "([Tipo] = N'Normal' AND [LocalEquipoId] IS NOT NULL AND [VisitanteEquipoId] IS NOT NULL AND [LocalEquipoId] <> [VisitanteEquipoId] AND [EquipoId] IS NULL AND [EquipoLocalId] IS NULL AND [LocalOVisitanteId] IS NULL)\n    OR\n    ([Tipo] = N'Libre' AND [EquipoLocalId] IS NOT NULL AND [LocalEquipoId] IS NULL AND [VisitanteEquipoId] IS NULL AND [EquipoId] IS NULL AND [LocalOVisitanteId] IS NULL)\n    OR\n    ([Tipo] = N'Interzonal' AND [EquipoId] IS NOT NULL AND [LocalOVisitanteId] IS NOT NULL AND [LocalEquipoId] IS NULL AND [VisitanteEquipoId] IS NULL AND [EquipoLocalId] IS NULL)\n    OR\n    ([Tipo] = N'SinEquipos' AND [LocalEquipoId] IS NULL AND [VisitanteEquipoId] IS NULL AND [EquipoId] IS NULL AND [EquipoLocalId] IS NULL AND [LocalOVisitanteId] IS NULL)");
                        });

                    b.HasDiscriminator().HasValue("Normal");
                });

            modelBuilder.Entity("Api.Core.Entidades.JornadaSinEquipos", b =>
                {
                    b.HasBaseType("Api.Core.Entidades.Jornada");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Jornada_Tipo_Valido", "([Tipo] = N'Normal' AND [LocalEquipoId] IS NOT NULL AND [VisitanteEquipoId] IS NOT NULL AND [LocalEquipoId] <> [VisitanteEquipoId] AND [EquipoId] IS NULL AND [EquipoLocalId] IS NULL AND [LocalOVisitanteId] IS NULL)\n    OR\n    ([Tipo] = N'Libre' AND [EquipoLocalId] IS NOT NULL AND [LocalEquipoId] IS NULL AND [VisitanteEquipoId] IS NULL AND [EquipoId] IS NULL AND [LocalOVisitanteId] IS NULL)\n    OR\n    ([Tipo] = N'Interzonal' AND [EquipoId] IS NOT NULL AND [LocalOVisitanteId] IS NOT NULL AND [LocalEquipoId] IS NULL AND [VisitanteEquipoId] IS NULL AND [EquipoLocalId] IS NULL)\n    OR\n    ([Tipo] = N'SinEquipos' AND [LocalEquipoId] IS NULL AND [VisitanteEquipoId] IS NULL AND [EquipoId] IS NULL AND [EquipoLocalId] IS NULL AND [LocalOVisitanteId] IS NULL)");
                        });

                    b.HasDiscriminator().HasValue("SinEquipos");
                });

            modelBuilder.Entity("Api.Core.Entidades.ZonaEliminacionDirecta", b =>
                {
                    b.HasBaseType("Api.Core.Entidades.Zona");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FaseId", "CategoriaId")
                        .IsUnique()
                        .HasFilter("[CategoriaId] IS NOT NULL");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Zonas_EliminacionDirecta_TieneCategoria", "([TipoZona] <> N'EliminacionDirecta') OR ([CategoriaId] IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("EliminacionDirecta");
                });

            modelBuilder.Entity("Api.Core.Entidades.ZonaTodosContraTodos", b =>
                {
                    b.HasBaseType("Api.Core.Entidades.Zona");

                    b.HasIndex("FaseId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Zonas_EliminacionDirecta_TieneCategoria", "([TipoZona] <> N'EliminacionDirecta') OR ([CategoriaId] IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("TodosContraTodos");
                });

            modelBuilder.Entity("Api.Core.Entidades.DelegadoClub", b =>
                {
                    b.HasOne("Api.Core.Entidades.Club", "Club")
                        .WithMany("DelegadoClubs")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Core.Entidades.Delegado", "Delegado")
                        .WithMany("DelegadoClubs")
                        .HasForeignKey("DelegadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Core.Entidades.EntidadesConValoresPredefinidos.EstadoDelegado", "EstadoDelegado")
                        .WithMany()
                        .HasForeignKey("EstadoDelegadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Delegado");

                    b.Navigation("EstadoDelegado");
                });

            modelBuilder.Entity("Api.Core.Entidades.Equipo", b =>
                {
                    b.HasOne("Api.Core.Entidades.Club", "Club")
                        .WithMany("Equipos")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Api.Core.Entidades.EquipoZona", b =>
                {
                    b.HasOne("Api.Core.Entidades.Equipo", "Equipo")
                        .WithMany("Zonas")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Core.Entidades.Zona", "Zona")
                        .WithMany("EquiposZona")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Api.Core.Entidades.Fase", b =>
                {
                    b.HasOne("Api.Core.Entidades.EntidadesConValoresPredefinidos.EstadoFase", "EstadoFase")
                        .WithMany()
                        .HasForeignKey("EstadoFaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Core.Entidades.Torneo", "Torneo")
                        .WithMany("Fases")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoFase");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("Api.Core.Entidades.FixtureAlgoritmoFecha", b =>
                {
                    b.HasOne("Api.Core.Entidades.FixtureAlgoritmo", "FixtureAlgoritmo")
                        .WithMany("Fechas")
                        .HasForeignKey("FixtureAlgoritmoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FixtureAlgoritmo");
                });

            modelBuilder.Entity("Api.Core.Entidades.HistorialDePagos", b =>
                {
                    b.HasOne("Api.Core.Entidades.JugadorEquipo", "JugadorEquipo")
                        .WithOne("HistorialDePagos")
                        .HasForeignKey("Api.Core.Entidades.HistorialDePagos", "JugadorEquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JugadorEquipo");
                });

            modelBuilder.Entity("Api.Core.Entidades.Jornada", b =>
                {
                    b.HasOne("Api.Core.Entidades.Fecha", "Fecha")
                        .WithMany("Jornadas")
                        .HasForeignKey("FechaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fecha");
                });

            modelBuilder.Entity("Api.Core.Entidades.JugadorEquipo", b =>
                {
                    b.HasOne("Api.Core.Entidades.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Core.Entidades.EntidadesConValoresPredefinidos.EstadoJugador", "EstadoJugador")
                        .WithMany("JugadorEquipos")
                        .HasForeignKey("EstadoJugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Core.Entidades.Jugador", "Jugador")
                        .WithMany("JugadorEquipos")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("EstadoJugador");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("Api.Core.Entidades.LeyendaTablaPosiciones", b =>
                {
                    b.HasOne("Api.Core.Entidades.TorneoCategoria", "Categoria")
                        .WithMany("LeyendasTablaPosiciones")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Core.Entidades.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Core.Entidades.Zona", "Zona")
                        .WithMany("LeyendasTablaPosiciones")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Equipo");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Api.Core.Entidades.Partido", b =>
                {
                    b.HasOne("Api.Core.Entidades.TorneoCategoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Core.Entidades.Jornada", "Jornada")
                        .WithMany("Partidos")
                        .HasForeignKey("JornadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Jornada");
                });

            modelBuilder.Entity("Api.Core.Entidades.Torneo", b =>
                {
                    b.HasOne("Api.Core.Entidades.Fase", "FaseApertura")
                        .WithMany()
                        .HasForeignKey("FaseAperturaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Core.Entidades.Fase", "FaseClausura")
                        .WithMany()
                        .HasForeignKey("FaseClausuraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Core.Entidades.TorneoAgrupador", "TorneoAgrupador")
                        .WithMany("Torneos")
                        .HasForeignKey("TorneoAgrupadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaseApertura");

                    b.Navigation("FaseClausura");

                    b.Navigation("TorneoAgrupador");
                });

            modelBuilder.Entity("Api.Core.Entidades.TorneoAgrupador", b =>
                {
                    b.HasOne("Api.Core.Entidades.EntidadesConValoresPredefinidos.Color", "Color")
                        .WithMany("Agrupadores")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Color");
                });

            modelBuilder.Entity("Api.Core.Entidades.TorneoCategoria", b =>
                {
                    b.HasOne("Api.Core.Entidades.Torneo", "Torneo")
                        .WithMany("Categorias")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("Api.Core.Entidades.Usuario", b =>
                {
                    b.HasOne("Api.Core.Entidades.Delegado", "Delegado")
                        .WithOne("Usuario")
                        .HasForeignKey("Api.Core.Entidades.Usuario", "DelegadoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Core.Entidades.EntidadesConValoresPredefinidos.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delegado");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Api.Core.Entidades.FechaEliminacionDirecta", b =>
                {
                    b.HasOne("Api.Core.Entidades.EntidadesConValoresPredefinidos.InstanciaEliminacionDirecta", "Instancia")
                        .WithMany()
                        .HasForeignKey("InstanciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Core.Entidades.ZonaEliminacionDirecta", "Zona")
                        .WithMany("Fechas")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instancia");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Api.Core.Entidades.FechaTodosContraTodos", b =>
                {
                    b.HasOne("Api.Core.Entidades.ZonaTodosContraTodos", "Zona")
                        .WithMany("Fechas")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Api.Core.Entidades.JornadaInterzonal", b =>
                {
                    b.HasOne("Api.Core.Entidades.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Core.Entidades.EntidadesConValoresPredefinidos.LocalVisitante", "LocalVisitante")
                        .WithMany()
                        .HasForeignKey("LocalOVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("LocalVisitante");
                });

            modelBuilder.Entity("Api.Core.Entidades.JornadaLibre", b =>
                {
                    b.HasOne("Api.Core.Entidades.Equipo", "EquipoLocal")
                        .WithMany()
                        .HasForeignKey("EquipoLocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipoLocal");
                });

            modelBuilder.Entity("Api.Core.Entidades.JornadaNormal", b =>
                {
                    b.HasOne("Api.Core.Entidades.Equipo", "LocalEquipo")
                        .WithMany()
                        .HasForeignKey("LocalEquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Core.Entidades.Equipo", "VisitanteEquipo")
                        .WithMany()
                        .HasForeignKey("VisitanteEquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocalEquipo");

                    b.Navigation("VisitanteEquipo");
                });

            modelBuilder.Entity("Api.Core.Entidades.ZonaEliminacionDirecta", b =>
                {
                    b.HasOne("Api.Core.Entidades.TorneoCategoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Core.Entidades.FaseEliminacionDirecta", "Fase")
                        .WithMany("Zonas")
                        .HasForeignKey("FaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Fase");
                });

            modelBuilder.Entity("Api.Core.Entidades.ZonaTodosContraTodos", b =>
                {
                    b.HasOne("Api.Core.Entidades.FaseTodosContraTodos", "Fase")
                        .WithMany("Zonas")
                        .HasForeignKey("FaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fase");
                });

            modelBuilder.Entity("Api.Core.Entidades.Club", b =>
                {
                    b.Navigation("DelegadoClubs");

                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("Api.Core.Entidades.Delegado", b =>
                {
                    b.Navigation("DelegadoClubs");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Api.Core.Entidades.EntidadesConValoresPredefinidos.Color", b =>
                {
                    b.Navigation("Agrupadores");
                });

            modelBuilder.Entity("Api.Core.Entidades.EntidadesConValoresPredefinidos.EstadoJugador", b =>
                {
                    b.Navigation("JugadorEquipos");
                });

            modelBuilder.Entity("Api.Core.Entidades.Equipo", b =>
                {
                    b.Navigation("Jugadores");

                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("Api.Core.Entidades.Fecha", b =>
                {
                    b.Navigation("Jornadas");
                });

            modelBuilder.Entity("Api.Core.Entidades.FixtureAlgoritmo", b =>
                {
                    b.Navigation("Fechas");
                });

            modelBuilder.Entity("Api.Core.Entidades.Jornada", b =>
                {
                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("Api.Core.Entidades.Jugador", b =>
                {
                    b.Navigation("JugadorEquipos");
                });

            modelBuilder.Entity("Api.Core.Entidades.JugadorEquipo", b =>
                {
                    b.Navigation("HistorialDePagos");
                });

            modelBuilder.Entity("Api.Core.Entidades.Torneo", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Fases");
                });

            modelBuilder.Entity("Api.Core.Entidades.TorneoAgrupador", b =>
                {
                    b.Navigation("Torneos");
                });

            modelBuilder.Entity("Api.Core.Entidades.TorneoCategoria", b =>
                {
                    b.Navigation("LeyendasTablaPosiciones");
                });

            modelBuilder.Entity("Api.Core.Entidades.Zona", b =>
                {
                    b.Navigation("EquiposZona");

                    b.Navigation("LeyendasTablaPosiciones");
                });

            modelBuilder.Entity("Api.Core.Entidades.FaseEliminacionDirecta", b =>
                {
                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("Api.Core.Entidades.FaseTodosContraTodos", b =>
                {
                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("Api.Core.Entidades.ZonaEliminacionDirecta", b =>
                {
                    b.Navigation("Fechas");
                });

            modelBuilder.Entity("Api.Core.Entidades.ZonaTodosContraTodos", b =>
                {
                    b.Navigation("Fechas");
                });
#pragma warning restore 612, 618
        }
    }
}
