// <auto-generated />
using System;
using Api.Persistencia._Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228234244_AgregaDelegadoClub")]
    partial class AgregaDelegadoClub
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Core.Entidades.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("Api.Core.Entidades.Delegado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstadoDelegadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("TelefonoCelular")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("EstadoDelegadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Delegados");
                });

            modelBuilder.Entity("Api.Core.Entidades.DelegadoClub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("DelegadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("DelegadoId", "ClubId")
                        .IsUnique();

                    b.ToTable("DelegadoClub");
                });

            modelBuilder.Entity("Api.Core.Entidades.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("TorneoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("TorneoId");

                    b.HasIndex(new[] { "Nombre", "TorneoId" }, "IX_Equipo_Nombre_TorneoId")
                        .IsUnique()
                        .HasFilter("[TorneoId] IS NOT NULL");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("Api.Core.Entidades.EstadoDelegado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EstadoDelegado");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Pendiente de aprobación"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Rechazado"
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Activo"
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.EstadoJugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EstadoJugador");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Fichaje pendiente de aprobación"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Fichaje rechazado"
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Activo"
                        },
                        new
                        {
                            Id = 4,
                            Estado = "Suspendido"
                        },
                        new
                        {
                            Id = 5,
                            Estado = "Inhabilitado"
                        },
                        new
                        {
                            Id = 6,
                            Estado = "Aprobado pendiente de pago"
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.HistorialDePagos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("JugadorEquipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JugadorEquipoId")
                        .IsUnique();

                    b.ToTable("HistorialDePagos");
                });

            modelBuilder.Entity("Api.Core.Entidades.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("Api.Core.Entidades.JugadorEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoJugadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFichaje")
                        .HasColumnType("datetime2");

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoJugadorId");

                    b.HasIndex("JugadorId");

                    b.HasIndex("EquipoId", "JugadorId")
                        .IsUnique();

                    b.ToTable("JugadorEquipo");
                });

            modelBuilder.Entity("Api.Core.Entidades.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Usuario"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Consulta"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Delegado"
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.Torneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Torneos");
                });

            modelBuilder.Entity("Api.Core.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreUsuario = "mati",
                            Password = "$2a$12$QB9FjCGu2zYdZFBCmB/16ulLqA2pId0VvxJ0VL5HN/Yiq9H/s/gJG",
                            RolId = 1
                        },
                        new
                        {
                            Id = 2,
                            NombreUsuario = "pipa",
                            Password = "$2a$12$STQqmm8mykCfe.Zwz1rFiOanM6zGajTUaF.Qc.l6zhY3BBKAXTYBy",
                            RolId = 1
                        },
                        new
                        {
                            Id = 101,
                            NombreUsuario = "consulta",
                            Password = "$2a$12$VfvDEk1W8Moj5nCmltl/xe/pRok4vSc1mekwuXq0LJFNngXy4m9HG",
                            RolId = 3
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.Delegado", b =>
                {
                    b.HasOne("Api.Core.Entidades.EstadoDelegado", "EstadoDelegado")
                        .WithMany("Delegados")
                        .HasForeignKey("EstadoDelegadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Core.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("EstadoDelegado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Api.Core.Entidades.DelegadoClub", b =>
                {
                    b.HasOne("Api.Core.Entidades.Club", "Club")
                        .WithMany("DelegadoClubs")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Core.Entidades.Delegado", "Delegado")
                        .WithMany("DelegadoClubs")
                        .HasForeignKey("DelegadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Delegado");
                });

            modelBuilder.Entity("Api.Core.Entidades.Equipo", b =>
                {
                    b.HasOne("Api.Core.Entidades.Club", "Club")
                        .WithMany("Equipos")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Core.Entidades.Torneo", "Torneo")
                        .WithMany("Equipos")
                        .HasForeignKey("TorneoId");

                    b.Navigation("Club");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("Api.Core.Entidades.HistorialDePagos", b =>
                {
                    b.HasOne("Api.Core.Entidades.JugadorEquipo", "JugadorEquipo")
                        .WithOne("HistorialDePagos")
                        .HasForeignKey("Api.Core.Entidades.HistorialDePagos", "JugadorEquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JugadorEquipo");
                });

            modelBuilder.Entity("Api.Core.Entidades.JugadorEquipo", b =>
                {
                    b.HasOne("Api.Core.Entidades.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Core.Entidades.EstadoJugador", "EstadoJugador")
                        .WithMany("JugadorEquipos")
                        .HasForeignKey("EstadoJugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Core.Entidades.Jugador", "Jugador")
                        .WithMany("JugadorEquipos")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("EstadoJugador");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("Api.Core.Entidades.Usuario", b =>
                {
                    b.HasOne("Api.Core.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Api.Core.Entidades.Club", b =>
                {
                    b.Navigation("DelegadoClubs");

                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("Api.Core.Entidades.Delegado", b =>
                {
                    b.Navigation("DelegadoClubs");
                });

            modelBuilder.Entity("Api.Core.Entidades.Equipo", b =>
                {
                    b.Navigation("Jugadores");
                });

            modelBuilder.Entity("Api.Core.Entidades.EstadoDelegado", b =>
                {
                    b.Navigation("Delegados");
                });

            modelBuilder.Entity("Api.Core.Entidades.EstadoJugador", b =>
                {
                    b.Navigation("JugadorEquipos");
                });

            modelBuilder.Entity("Api.Core.Entidades.Jugador", b =>
                {
                    b.Navigation("JugadorEquipos");
                });

            modelBuilder.Entity("Api.Core.Entidades.JugadorEquipo", b =>
                {
                    b.Navigation("HistorialDePagos");
                });

            modelBuilder.Entity("Api.Core.Entidades.Torneo", b =>
                {
                    b.Navigation("Equipos");
                });
#pragma warning restore 612, 618
        }
    }
}
